<?php

declare(strict_types=1);

namespace Tests\Services;

use App\Core\Database;
use App\Exceptions\InvalidUrlException;
use App\Services\URLService;
use PHPUnit\Framework\TestCase;

class URLServiceTest extends TestCase
{
    private URLService $service;

    protected function setUp(): void
    {
        $this->service = new URLService();

        Database::migrate();

        $pdo = Database::getConnection();
        $pdo->exec('DELETE FROM clicks');
        $pdo->exec('DELETE FROM urls');
    }

    public function testShortenCreatesUrlWithAutoGeneratedCode(): void
    {
        $url = $this->service->shorten('https://example.com');

        $this->assertNotNull($url->getId());
        $this->assertEquals('https://example.com', $url->getOriginalUrl());
        $this->assertNotEmpty($url->getShortCode());
        $this->assertNull($url->getCustomAlias());
    }

    public function testShortenCreatesUrlWithCustomAlias(): void
    {
        $url = $this->service->shorten('https://example.com', 'my-link');

        $this->assertEquals('my-link', $url->getCustomAlias());
        $this->assertEquals('my-link', $url->getDisplayCode());
    }

    public function testShortenRejectsInvalidUrl(): void
    {
        $this->expectException(InvalidUrlException::class);
        $this->service->shorten('not-a-url');
    }

    public function testShortenRejectsInvalidScheme(): void
    {
        $this->expectException(InvalidUrlException::class);
        $this->service->shorten('ftp://example.com');
    }

    public function testShortenRejectsDuplicateCustomAlias(): void
    {
        $this->service->shorten('https://example.com', 'taken-alias');

        $this->expectException(InvalidUrlException::class);
        $this->service->shorten('https://example.org', 'taken-alias');
    }

    public function testShortenRejectsReservedAlias(): void
    {
        $this->expectException(InvalidUrlException::class);
        $this->service->shorten('https://example.com', 'admin');
    }

    public function testShortenRejectsTooShortAlias(): void
    {
        $this->expectException(InvalidUrlException::class);
        $this->service->shorten('https://example.com', 'ab');
    }

    public function testResolveReturnsUrl(): void
    {
        $created = $this->service->shorten('https://example.com');
        $resolved = $this->service->resolve($created->getShortCode());

        $this->assertEquals($created->getId(), $resolved->getId());
    }

    public function testResolveThrowsForNonexistentCode(): void
    {
        $this->expectException(\App\Exceptions\UrlNotFoundException::class);
        $this->service->resolve('nonexistent');
    }

    public function testDeleteRemovesUrl(): void
    {
        $url = $this->service->shorten('https://example.com');
        $result = $this->service->delete($url->getId());

        $this->assertTrue($result);

        $this->expectException(\App\Exceptions\UrlNotFoundException::class);
        $this->service->getById($url->getId());
    }
}